### PR TITLE
Include message lists in the json response for a queue.

### PR DESCRIPTION
**Pull request by jbussdieker**
Not sure this is complete enough to start implementing live-update of the views but this would be useful for more granular monitoring.

```
$ curl -s http://localhost:3333/q/tester.json | json_pp
{
   "uptime" : 1244,
   "status" : "UP",
   "messages" : {
      "que" : [
         [
            "20150420.2002.22.491.4337777",
            1429560142
         ],
         [
            "20150420.2002.18.641.4337771",
            1429560138
         ]
      ],
      "run" : [
         [
            "20150420.2002.14.602.4337762",
            "que"
         ]
      ],
      "done" : [
         "20150420.1945.53.550.4337060",
         "20150420.1945.40.244.4337048",
         "20150420.1944.12.185.4337011",
         "20150420.1943.51.860.4336990"
      ],
      "err" : [
         "20150420.1943.31.613.4336971"
      ],
      "prep" : []
   },
   "run_size" : 1,
   "que_size" : 2,
   "done_size" : 4,
   "err_size" : 1,
   "prep_size" : 0,
   "relayed_size" : 0
}
```

### CODE REVIEW

**Comment by sodabrew** [comment]
I wonder what the `1429560142 ` is in the que array, and the `que` in the run array? I don't think a limit is needed in the json output.

We'll need two (or two kinds) of JSON endpoints for full live updating: one for the homepage, which only needs the number of messages and status of each queue, and one for an individual queue, which also needs the arrays of message ids.

I vaguely think that changing the per-queue json to have message arrays makes sense as you've done here, and a new all-queues endpoint is needed that provides status for all queues in one response.

**Comment by tjeezy** [comment]
@sodabrew `1429560142` in the que array is when the message is "due" and `que` in the run array is the message's "status" (see https://github.com/brightroll/rq/blob/d9de00cfb54840b0f0de004138a71802ab2d9460/code/queue.rb#L1632).

**Comment by tjeezy** [comment]
Would probably be cleaner to enforce the same "schema" on each queue array rather than just `to_json` each...

**Comment by jbussdieker** [comment]
It looks like the extra info would be required for the live-update feature based on how we currently render the HTML view https://github.com/brightroll/rq/blob/d9de00cfb54840b0f0de004138a71802ab2d9460/code/views/queue.erb#L63-L69.

**Comment by jbussdieker** [comment]
Sorry I believe the ref I was looking for is here: https://github.com/brightroll/rq/blob/d9de00cfb54840b0f0de004138a71802ab2d9460/code/views/queue.erb#L83 where we provide some sort of timer (which is usually negative possibly a bug)

**Comment by sodabrew** [comment]
The negative timer means the job was queued with an immediate due date, and the "past-due time" is the time since it was queued.

**Comment by sodabrew** [comment]
Are you up for a deeper refactor? I'd like to change these field-pair arrays to hashes. If any particular que state requires extra fields, they should be tagged in the hash. It means an extra level of depth without extra data, but so what. It also means queue.erb can be cut to 1/5 of its current size by re-using the same code for each column.

```
{
  "messages": {
    "run": [
      { "msg_id": 12345,
        "msg_url": "http://host:3333/q/queuename/12345",
        "due": 7654124,
        "status": "run",
      }, ...
    ],
  },
}

```

**Comment by jbussdieker** [comment]
That sounds like a good idea. I should have some time to work on that later today.

**Comment by sodabrew** [comment]
Let's revisit this soon!

**Pull request closed without merging**
